# Generated by Django 4.1.3 on 2022-11-28 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Carousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Image", models.ImageField(null=True, upload_to="Carousel")),
                ("Img_title", models.CharField(max_length=30, null=True)),
                ("Img_desc", models.CharField(max_length=500, null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("text_introduction", models.TextField(null=True)),
                (
                    "image",
                    models.ImageField(
                        default="posts/default.jpg", upload_to="images/posts"
                    ),
                ),
                ("slug", models.SlugField(max_length=250, unique_for_date="publish")),
                ("publish", models.DateTimeField(default=django.utils.timezone.now)),
                ("content", models.TextField()),
                ("text_location", models.TextField(null=True)),
                (
                    "image_location",
                    models.ImageField(
                        default="posts/default.jpg", upload_to="images/posts"
                    ),
                ),
                ("text_weight", models.TextField(null=True)),
                ("text_size", models.TextField(null=True)),
                ("text_class", models.TextField(null=True)),
                ("text_order", models.TextField(null=True)),
                ("text_family", models.TextField(null=True)),
                (
                    "image_2",
                    models.ImageField(
                        default="posts/default.jpg", upload_to="images/posts"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="blog.category",
                    ),
                ),
            ],
            options={"ordering": ("-publish",),},
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("content", models.TextField()),
                ("publish", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField(default=True)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="blog.comment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.post",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
